name: Vérification du respect des spécifications

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate JSON
      uses: docker://orrosenblatt/validate-json-action:latest
      env:
        INPUT_SCHEMA: schema_amenagements_cyclables.json
        INPUT_JSONS: exemple-valide.json